import 'package:dynamic_ui/svgs/bed.dart';
import 'package:dynamic_ui/svgs/cabinet.dart';
import 'package:dynamic_ui/svgs/chair.dart';
import 'package:dynamic_ui/svgs/dining.dart';
import 'package:dynamic_ui/svgs/discount.dart';
import 'package:dynamic_ui/svgs/sbi.dart';
import 'package:dynamic_ui/svgs/sofa.dart';
import 'package:dynamic_ui/svgs/storage.dart';
import 'package:dynamic_ui/svgs/study.dart';
import 'package:dynamic_ui/svgs/svg_icons.dart';
import 'package:dynamic_ui/svgs/table.dart';

final encodedRecycle = Uri.encodeComponent(recycle);
final encodedBox = Uri.encodeComponent(box);
final encodedTable = Uri.encodeComponent(table);
final encodedChair = Uri.encodeComponent(chair);
final encodedbed = Uri.encodeComponent(bed);
final encodedstorage = Uri.encodeComponent(storage);
final encodeddining = Uri.encodeComponent(dining);
final encodedStudy = Uri.encodeComponent(study);
final encodedSofa = Uri.encodeComponent(sofa);
final encodedDsicount = Uri.encodeComponent(discount);
final encodedCabinet = Uri.encodeComponent(cabinet);
final encodedSbi = Uri.encodeComponent(sbi);